### PR TITLE
Added random Halloween facts and adjusted styles

### PR DESCRIPTION
**Pull request by brandonstinson**
Added an H3 with some random Halloween facts. Adding to the facts array could be an opportunity for some first time pull requests.

### CODE REVIEW

**Comment by scrabill** [comment]
I love this idea! Do you have a resource/reference for any of your facts?

**Comment by brandonstinson** [comment]
I got them all from [here](https://www.womansday.com/life/g485/15-fascinating-halloween-facts-124464/).

**Comment by scrabill** [comment]
Cool! I haven't forgotten about this addition. There's a conflict between this and some newer code in the js file.

**Comment by scrabill** [comment]
@brandonstinson

[I finally got this added](https://github.com/scrabill/how-many-days-until-halloween/commit/8af559ad0017bb1965c70c9435c618f2fd37cfdb)!

I've created issue #226 if anyone wants to add a new fact

Thank you for this addition!

**Pull request merged**
