### PR TITLE
Major changes to the website

### PR DESCRIPTION
**Pull request by juanluischaurant**
* Added animated background
* Animated clouds
* New font families
* Fixed background
* Organized code in general

### CODE REVIEW

**Comment by nbuss848** [comment]
I like these changes, but it seems like the stars in the background take awhile to load. Is there a way to speed that up?

**Comment by juanluischaurant** [comment]
Hello @nbuss848, thanks for checking out the changes.
I have been thinking about this little issue and checking the code in general.

 I found that in  order to successfully optimize the load time we need to:

* Clean the code in general (Deleting unnecessary stuff)
*  Reduce External HTTP Requests (Maybe here is the problem with the stars)
*  Optimize the images for web
(Needed changes are not limited to the three listed above)

What do you think about?

**Comment by nbuss848** [comment]
I think it might be super cool if this was the page that would show up on Halloween. 
Of course, it is missing the dancing pumpkin gif, but that is easily fixed :).

I also think that your plan of attack is spot on if the owner of the repo likes the changes.

I think maybe the flying bats might have been special to the original creator so if those could come back in some fashion that would be cool too.

**Comment by scrabill** [comment]
@juanluischaurant @nbuss848 - Loving the back and forth. I'll be looking over these additions shortly.

**Comment by juanluischaurant** [comment]
@nbuss848 Thanks for your observations, sadly I had no time to make more changes until today, so maybe the next year.

@scrabill thanks, it means a lot that you appreciate it. I have done several changes, do you think it will give us troubles?

**Pull request closed without merging**
