### PR TITLE
Adding Home page

### PR DESCRIPTION
**Pull request by paniya**

### CODE REVIEW

**Comment by paniya** [comment]
Expanding the home page

**Comment by scrabill** [comment]
@paniya 

I love the addition of the music! However, I do see the addition of a Wordpress theme. That'll require a database, additional server space, etc which is a little more involved than I would like to have for this project.

Would you be able to add the background music to the bootstrap page?

Let me know if you have any questions.

**Comment by paniya** [comment]
Sure I will add it to js file. Glad you liked it :-)

*Praneeth Perera*
Undergraduate in University of Colombo School of Computing
IEEEXtreme Country Lead
Member of  ACM
Member of ICASL

Email  : praneethperera24@gmail.com/ praneethperera@ieee.org
Mobile : +94 77 85 89 445

**Comment by scrabill** [comment]
@paniya - I thought I resolved all conflicts correctly, and I see the `<embed>` code on the index.html file, but the music isn't playing. Do you have any insight on what I'm missing?

**Comment by paniya** [comment]
checked the src is correct!

*Praneeth Perera*
Undergraduate in University of Colombo School of Computing
IEEEXtreme Country Lead
Member of  ACM
Member of ICASL

Email  : praneethperera24@gmail.com/ praneethperera@ieee.org
Mobile : +94 77 85 89 445

**Pull request merged**
